# Site settings
title: Cofal<font color="#F3D085">の</font>ブログ
SEOTitle: Cofalのブログ
header-img: img/post-bg-desk.webp
email: cofalconer@gmail.com
description: "Failures would not become success's mother without your mind!"
keyword: "へいぎ, cofal, 袁学"
url: "http://cofal.work"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/fredcof/" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "俺の日記と俺のブログ。"
sidebar-avatar: /img/about-cofal-gentle.webp      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
github_username:    FredCof
facebook_username:  smith.fred.16503323
weibo_username:     6278667439
bilibili_username:  44685985

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.

permalink: pretty
paginate: 6

exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
# highlight: true
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 1bf20f61497f9140573a                            #生成的clientID
  clientSecret: 6ee9ec70fccb5f1a598425c02a211ef03378f30c    #生成的clientSecret
  repo: fredcof.github.io    #仓库名称
  owner: FredCof    #github用户名
  admin: FredCof
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 2c802826c39d91a631b68e518d6cab55

# Google Analytics
ga_track_id: 'UA-132577144-1'              # Format: UA-xxxxxx-xx
ga_domain: cofal.work                     # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Reward QRcode
QRcodes: [
    ["微信","img/About/wechat.png"],
    ["支付宝","img/About/ali.png"]
]

# Friends
friends: [
    {
        title: "every-2.top",
        icon: "/img/friend_link/every2.png",
        href: "https://every-2.top/"
    }
]
